# Generated by Django 4.0.6 on 2022-08-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_contract_contract_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_status_id',
            new_name='event_status',
        ),
    ]
