# Generated by Django 4.0.6 on 2022-08-11 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_rename_event_status_id_event_event_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientCustomer',
        ),
    ]
