# Generated by Django 4.0.6 on 2022-08-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_client_clientcustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='client',
            new_name='client_customer',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='client',
            new_name='client_customer',
        ),
    ]
