# Generated by Django 4.0.6 on 2022-08-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_client_contract_client_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomer',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
