# Generated by Django 4.0.6 on 2022-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_clientcustomer_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
