# Generated by Django 4.0.6 on 2022-08-12 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_contract_date_updated_alter_event_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='events.eventstatus'),
        ),
    ]
